import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import PageWrapper from "@/components/pagewrapper/PageWrapper";
import SessionProviderWrapper from "@/components/auth/SessionProviderWrapper";
import TopNavWrapper from "@/components/pagewrapper/TopNavWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" suppressHydrationWarning>
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased {overflow-hidden [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]}` }
      >
        <SessionProviderWrapper>
        <TopNavWrapper/>
        <Toaster position="top-right" />
        <main>
          <PageWrapper>
          {children}
          </PageWrapper>
        </main>
        


        </SessionProviderWrapper>
        
      </body>
     
    </html>
  );
}
