export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { BlogProvider } from "@/context/blog";

import PageWrapper from "@/components/pagewrapper/PageWrapper";
import SessionProviderWrapper from "@/components/auth/SessionProviderWrapper";
import TopNavWrapper from "@/components/pagewrapper/TopNavWrapper";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" suppressHydrationWarning>
     
      <BlogProvider>

        <body
           className={`
        ${geistSans.variable}
        ${geistMono.variable}
        antialiased
        bg-zinc-900 text-zinc-100
        overflow-x-hidden
        scrollbar-none
        selection:bg-blue-500/30 selection:text-white
      `}
      >
        <SessionProviderWrapper>
        <TopNavWrapper/>
        <Toaster position="top-right" />
        <main className="relative">
               <div className="pointer-events-none fixed inset-0 -z-10
                          bg-linear-to-br from-blue-500/5 via-transparent to-purple-500/5" />
          <PageWrapper>
          {children}
          </PageWrapper>
        </main>
        
       <Footer />


        </SessionProviderWrapper>
        
      </body>
      </BlogProvider>
     
    </html>
  );
}
